### PR TITLE
shardtree: Fix shardtree cap corruption resulting from a bug in `root_caching`.

### LINKED ISSUE #2145: zcash_client_sqlite: Note commitment tree corruption error.
The following error has been reported a number of times:

```
Error: [ZCBPEO0022] Put Orchard subtree roots to the DB failed.
  compactBlockProcessorPutOrchardSubtreeRoots(ZcashLightClientKit.ZcashError.rustPutOrchardSubtreeRoots("Error while storing Orchard subtree roots: An error occurred
  persisting or retrieving tree data: Commitment tree serialization error: Note commitment tree cap was invalid at address Address { level: Level(0), index: 755 }"))
```

This indicates an error in note commitment tree deserialization when reading from the shard database; the note commitment tree cap is being corrupted by some previous operation and then encoded.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes zcash/librustzcash#2145

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK. @str4d should also review.

File: shardtree/src/lib.rs [hunk 1]
```diff
@@ -765,7 +765,10 @@ impl<
         match &cap.root.0 {
             Node::Parent { ann, left, right } => {
                 match ann {
-                    Some(cached_root) if target_addr.contains(&cap.root_addr) => {
+                    Some(cached_root)
+                        if target_addr.contains(&cap.root_addr)
+                            && truncate_at >= cap.root_addr.position_range_end() =>
```
Comment (str4d) [inline shardtree/src/lib.rs]: It annoys me a little that these two conditions are in the reverse order to the `Leaf` handler check.

**Review by str4d — APPROVED** [review]
utACK 513972bd716b37246075c9748a9f49e9bd210f0a.

Same question applies here about whether this should be on a `shardtree` maintenance branch vs `main` as in https://github.com/zcash/incrementalmerkletree/pull/139#pullrequestreview-3811066872.
